[build]
  # Directory where the build command will run
  base = "demo-project-1"
  # Command to build your Angular project
  command = "ng build"

  # Directory to publish (relative to root of your repository)
  publish = "demo-project-1/dist/my-first-app"

[[redirects]]
  # Redirect all requests to the index.html for Angular routing to work
  from = "/*"
  to = "/index.html"
  status = 200
